#!/usr/bin/env bash

# https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:team-xbmc/ppa
sudo apt-get update
sudo apt-get install kodi
