#!/usr/bin/env bash

cd /tmp

# https://albertlauncher.github.io/docs/installing/

curl https://build.opensuse.org/projects/home:manuelschneid3r/public_key | sudo apt-key add -

# https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert

echo 'deb http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/home:manuelschneid3r.list
sudo wget -nv https://download.opensuse.org/repositories/home:manuelschneid3r/xUbuntu_20.04/Release.key -O "/etc/apt/trusted.gpg.d/home:manuelschneid3r.asc"
sudo apt update
sudo apt install albert
