#!/usr/bin/env bash

# The version in ubuntu is having issue, can't open the window, before it's fixed, need to build manually
# https://github.com/CristianHenzel/ClipIt/issues/137

if [ -z $1 ] ; then
    FOLDER=/tmp
fi
    FOLDER=$1
cd

if [ -d ${FOLDER}/ClipIt ] ; then
    cd ${FOLDER}/ClipIt
    git pull
else
    cd $FOLDER
    git clone https://github.com/jemyzhang/ClipIt.git
    cd ClipIt
fi

echo "Installing dependencies with `apt build-dep clipit` (need to provide sudo password)"
sudo apt build-dep clipit

# echo ""
# echo "Installing build tools"
# sudo apt install build-essential automake autopoint intltool

echo ""
echo "Running autogen.sh"
./autogen.sh

echo ""
echo "Running configure, using gtk3, and add appindicator support"
./configure --enable-appindicator=yes --with-gtk3

echo ""
echo "Running make"
make

echo ""
echo "Installing to /usr/local"
sudo make install

echo ""
echo "Uninstalling clipit from apt (if installed before)"
sudo apt remove clipit

echo ""
echo "If you still having issue with the history windows not showing, try increase the delay in source (check last commit for detail)"
