# See https://github.com/dart-lang/mono_repo for details
stages:
  - format_analyzer_tests:
    - group:
      - dartanalyzer: --fatal-infos --fatal-warnings .
      - dartfmt
      dart: [dev]
    - group:
      - dartanalyzer: --fatal-warnings .
      dart: [2.0.0]
    - group:
      - test
      dart: [2.0.0, dev]
