#!/usr/bin/env bash

# http://unix.stackexchange.com/questions/166121/using-xbindkeys-to-bind-the-meta-key-a-k-a-super-key-windows-key-to-left-cl

echo "Before Remap"
xmodmap -pm | grep mod1
xmodmap -pk | grep Alt_R
xmodmap -pm | grep mod3

xmodmap -e "remove mod1 = Alt_R"
xmodmap -e "add mod3 = Alt_R"

echo "After Remap"
xmodmap -pm | grep mod1
xmodmap -pk | grep Alt_R
xmodmap -pm | grep mod3


