[alias]
b = "build"
c = "check"
t = "test"

r = "run"
rr = "run --release"
rf = "run --features"
rrf = "run --release --features"

d = "run --features dev"
n = "run --features native"
s = "make serve"

f = "fix"
m = "fmt --all"

[build]
rustc-wrapper = "sccache"
