#!/bin/bash

curl -vsSL https://raw.github.com/Homebrew/linuxbrew/go/install > ~/.dotfiles/bootstrap/linux/bootstrap-linuxbrew

curl -vsSL https://install.direct/go.sh > ~/.dotfiles/bootstrap/linux/bootstrap-v2ray.sh

chmod 755 ~/.dotfiles/bootstrap/linux/*
