let g:dotvim_settings = {}
let g:dotvim_settings.version = 1

let g:dotvim_settings.default_indent = 4
let g:dotvim_settings.max_column = 0
let g:dotvim_settings.enable_cursorcolumn = 1
let g:dotvim_settings.autocomplete_method = 'ycm'

let g:dotvim_settings.disabled_plugins = [
            \   "justinmk/vim-sneak",
            \   "tpope/vim-speeddating",
            \   "tpope/vim-dispatch",
            \   "mbbill/undotree",
            \]

if has('vim_starting')
    if &compatible
        set nocompatible
        " Be iMproved
    endif
    " Required:
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#begin(expand('~/.vim/bundle/'))

source ~/.dotfiles/vim/sling.vim

source ~/.vimrc.after

call neobundle#end()
NeoBundleCheck
