# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" "hid_multitouch" ];
  boot.blacklistedKernelModules = [ "mei" "mei_me" "mei_wdt" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.crypted.device = "/dev/disk/by-id/nvme-eui.0025386cf100473f-part2";
  boot.supportedFilesystems = [ "zfs" ];

  boot.loader.grub = {
    devices = [ "/dev/nvme0n1" ];
    gfxmodeEfi = "1280x720";
    font = "/boot/grub.otf";
    fontSize = 32;
  };

  services.xserver.displayManager.sddm.autoLogin.enable = true;
  services.xserver.synaptics = {
    buttonsMap = [ 1 3 2 ];
    minSpeed = "1.0";
    maxSpeed = "1.5";
    accelFactor = "0.002";
  };

  fileSystems."/" =
    { device = "rpool/root/nixos";
      fsType = "zfs";
    };

  fileSystems."/home" =
    { device = "rpool/home";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3AFA-4B05";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "powersave";
  networking.hostId = "91278545";

  hardware.pulseaudio = {
   enable = true;
   support32Bit = true; # This might be needed for Steam games
   package = pkgs.pulseaudioFull;
  };

  hardware.bluetooth.enable = true;
}
