#!/usr/bin/env bash

# http://unix.stackexchange.com/questions/166121/using-xbindkeys-to-bind-the-meta-key-a-k-a-super-key-windows-key-to-left-cl

echo "Before Remap"
xmodmap -pm | grep shift
xmodmap -pk | grep Shift_R
xmodmap -pk | grep Up

xmodmap -e "remove shift = Shift_R"
xmodmap -e "keycode 62 = Up"
xset -r 62

echo "After Remap"
xmodmap -pm | grep shift
xmodmap -pk | grep Shift_R
xmodmap -pk | grep Up


