# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "uas" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fcc1cd90-4faa-4452-91b5-97e03df6a987";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/51ED-5AA6";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;

  # virtualisation.virtualbox.guest.enable = true;

  # services.xserver.videoDrivers = [
  #  "nvidia"
    # "ati_unfree"
  #];

  hardware.pulseaudio = {
   enable = true;
   support32Bit = true; # This might be needed for Steam games
   package = pkgs.pulseaudioFull;
 };

  hardware.bluetooth.enable = true;
}
