call dein#add('tpope/vim-fugitive')
call dein#add('tpope/vim-dispatch')
call dein#add('tpope/vim-salve')
call dein#add('tpope/vim-projectionist')
call dein#add('tpope/vim-fireplace')
call dein#add('tpope/vim-repeat')
call dein#add('tpope/vim-sexp-mappings-for-regular-people')
