#!/usr/bin/env bash
# https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

curl -sL https://deb.nodesource.com/setup_8.x > /tmp/node_setup_8.x
sudo bash /tmp/node_setup_8.x
sudo apt-get install nodejs

