# set -x SPACEFISH_CHAR_SYMBOL ">>="

set -x SPACEFISH_PROMPT_ADD_NEWLINE false
set -x SPACEFISH_PROMPT_SEPERATOR_SHOW true

#if test (uname) = "Darwin"
#    set -x SPACEFISH_PROMPT_SEPERATOR_COLOR brblack
#end

set -x SPACEFISH_TIME_SHOW true

set -x SPACEFISH_DIR_TRUNC 0
set -x SPACEFISH_DIR_TRUNC_REPO false

set -x SPACEFISH_EXEC_TIME_ELAPSED 0

set -x SPACEFISH_EXIT_CODE_SHOW true
set -x SPACEFISH_EXIT_CODE_SYMBOL ""

set -x SPACEFISH_DOTNET_SHOW true

set -x SPACEFISH_BATTERY_SHOW false
