#!/usr/bin/env bash
# https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish

cd /tmp
wget http://download.opensuse.org/repositories/shells:fish:release:2/Debian_8.0/Release.key
apt-key add - < Release.key
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/ /' > /etc/apt/sources.list.d/fish.list 
apt-get update
apt-get install fish
