#!/usr/bin/env bash

curl -O https://download.arangodb.com/arangodb32/xUbuntu_16.04/Release.key
sudo apt-key add - < Release.key

echo 'deb https://download.arangodb.com/arangodb32/xUbuntu_16.04/ /' | sudo tee /etc/apt/sources.list.d/arangodb.list
sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install arangodb3=3.2.9
